name: extender
description: Provides additional capabilities for most standard and popular types and classes.
version: 1.0.0
repository: https://github.com/iLnaar/extender

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

dependencies:
  decimal: ^2.0.0
  quiver: ^3.0.1+1
  rational: ^2.0.0
